site_name: Breakout of the Pongeon TDD
nav:
    - Home: 'index.md'
    - 'Conventions':
        - "Version Control": 'conventions/versioncontrol.md'
        - "Code Standards": 'conventions/codestandards.md'
        - "Project Structure": 'conventions/projectstructure.md'
    - 'Assets':
        - "Sounds": 'assets/sounds.md'
        - "Sprites": 'assets/sprites.md'
    - 'Processes':
        - "Public Variables": 'processes/public_variables.md'
